name: "Copilot Setup Steps"

# Automatically run the setup steps when they are changed to allow for easy validation, and
# allow manual testing through the repository's "Actions" tab
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

jobs:
  # The job MUST be called `copilot-setup-steps` or it will not be picked up by Copilot.
  copilot-setup-steps:
    runs-on: ubuntu-latest
    env:
      BAR: foo
      JIRA_INSTANCE_URL: https://zapierorg.atlassian.net
      COPILOT_JIRA_INSTANCE_URL: https://zapierorg.atlassian.net
      JIRA_USER_EMAIL: fokke.zandbergen@zapier.com
      COPILOT_JIRA_USER_EMAIL: fokke.zandbergen@zapier.com
      JIRA_API_KEY: dummy
      COPILOT_MCP_JIRA_API_KEY: dummy
      THE_COPILOT_MCP_SEC: ${{ secrets.COPILOT_MCP_SEC }}
      THE_REPO_SEC: ${{ secrets.REPO_SEC }}
    steps:
      - name: Check variable
        run: |
          echo $COPILOT_MCP_FOO
          echo $FOO
          echo $BAR
          echo $JIRA_INSTANCE_URL
          echo $COPILOT_JIRA_INSTANCE_URL
          echo $THE_COPILOT_MCP_SEC
          echo $THE_REPO_SEC
